<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfileUpdateRequest;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Redirect;
use Inertia\Inertia;
use Inertia\Response;

class ProfileController extends Controller
{
    /**
     * Display the user's profile form.
     */
    public function edit(Request $request): Response
    {
        $user = $request->user();
        if ($user->employee) {
            $user->load('employee.qualifications', 'employee.previousOrganizations');
        }

        return Inertia::render('Profile/Edit', [
            'mustVerifyEmail' => $request->user() instanceof MustVerifyEmail,
            'status' => session('status'),
            'employee' => $user->employee,
        ]);
    }

    /**
     * Update the user's profile information.
     */
    public function update(ProfileUpdateRequest $request): RedirectResponse
    {
        $request->user()->fill($request->validated());

        if ($request->user()->isDirty('email')) {
            $request->user()->email_verified_at = null;
        }

        $request->user()->save();

        return Redirect::route('profile.edit');
    }

    public function updateEmployee(Request $request): RedirectResponse
    {
        $user = $request->user();
        $employee = $user->employee;

        if (!$employee) {
            return Redirect::route('profile.edit')->withErrors(['employee' => 'No HR profile attached to this account.']);
        }

        $validated = $request->validate([
            'first_name' => 'required|string|max:255',
            'middle_name' => 'nullable|string|max:255',
            'last_name' => 'required|string|max:255',
            'contact_no' => 'required|string|max:20',
            'alternate_no' => 'nullable|string|max:20',
            'current_address' => 'required|string',
            'permanent_address' => 'required|string',
            'skills' => 'nullable|string',
            'experience' => 'nullable|string',
            
            // Dynamic Arrays
            'qualifications' => 'nullable|array',
            'qualifications.*.degree' => 'required_with:qualifications|string',
            'qualifications.*.institution' => 'required_with:qualifications|string',
            'qualifications.*.year' => 'required_with:qualifications|string',
            
            'previous_organizations' => 'nullable|array',
            'previous_organizations.*.company_name' => 'required_with:previous_organizations|string',
            'previous_organizations.*.designation' => 'required_with:previous_organizations|string',
            'previous_organizations.*.duration' => 'required_with:previous_organizations|string',
            
            'professional_photo' => 'nullable|file|mimes:jpeg,png,jpg,webp|max:2048',
            'casual_photo' => 'nullable|file|mimes:jpeg,png,jpg,webp|max:2048',
            'adhar_upload' => 'nullable|file|mimes:pdf,jpeg,png,jpg,webp|max:5000',
            'salary_slips.*' => 'nullable|file|mimes:pdf,jpeg,png,jpg,webp|max:5000',
        ]);

        $employee->update([
            'first_name' => $validated['first_name'],
            'middle_name' => $validated['middle_name'],
            'last_name' => $validated['last_name'],
            'contact_no' => $validated['contact_no'],
            'alternate_no' => $validated['alternate_no'],
            'current_address' => $validated['current_address'],
            'permanent_address' => $validated['permanent_address'],
            'skills' => $validated['skills'],
            'experience' => $validated['experience'],
        ]);

        // Replace qualifications
        $employee->qualifications()->delete();
        if (!empty($validated['qualifications'])) {
            foreach ($validated['qualifications'] as $q) {
                // Ignore empty artifacts generated by Vue
                if (!empty($q['degree'])) {
                    $employee->qualifications()->create([
                        'qualification' => $q['degree'],
                        'institution' => $q['institution'] ?? '',
                        'year' => $q['year'] ?? '',
                    ]);
                }
            }
        }

        // Replace Previous Organizations
        $employee->previousOrganizations()->delete();
        if (!empty($validated['previous_organizations'])) {
            foreach ($validated['previous_organizations'] as $index => $po) {
                if (!empty($po['company_name'])) {
                    $org = $employee->previousOrganizations()->create([
                        'company_name' => $po['company_name'],
                        'designation' => $po['designation'] ?? '',
                        'duration' => $po['duration'] ?? '',
                    ]);

                    if ($request->hasFile("salary_slips.{$index}")) {
                        $path = $request->file("salary_slips.{$index}")->store('documents', 'public');
                        \App\Models\Document::create([
                            'employee_id' => $employee->id,
                            'type' => 'salary_slip_' . $org->id,
                            'path' => $path
                        ]);
                    }
                }
            }
        }

        $fileTypes = ['professional_photo', 'casual_photo', 'adhar_upload'];
        foreach ($fileTypes as $type) {
            if ($request->hasFile($type)) {
                $path = $request->file($type)->store('documents', 'public');
                \App\Models\Document::create([
                    'employee_id' => $employee->id,
                    'type' => $type,
                    'path' => $path
                ]);
            }
        }

        return Redirect::route('profile.edit')->with('status', 'employee-updated');
    }
}
